// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCisOMw1iSr0UztUVjsIP6bokQ1mU9y96Y',
    appId: '1:909888987040:web:b369750adc3a8724bc0ec5',
    messagingSenderId: '909888987040',
    projectId: 'rover-testing',
    authDomain: 'rover-testing.firebaseapp.com',
    storageBucket: 'rover-testing.appspot.com',
    measurementId: 'G-LGLE825PJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Msar5uzj5jTJdH6X41Dh3nh9VgqjqlM',
    appId: '1:909888987040:android:bcfa88ed84416423bc0ec5',
    messagingSenderId: '909888987040',
    projectId: 'rover-testing',
    storageBucket: 'rover-testing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTs96NaJO0e4eNnPVUTLCWBMrTuKDvsuM',
    appId: '1:909888987040:ios:cab963f00c0cfb57bc0ec5',
    messagingSenderId: '909888987040',
    projectId: 'rover-testing',
    storageBucket: 'rover-testing.appspot.com',
    iosBundleId: 'com.rovertaxi.testUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTs96NaJO0e4eNnPVUTLCWBMrTuKDvsuM',
    appId: '1:909888987040:ios:510bf59b53d86b4dbc0ec5',
    messagingSenderId: '909888987040',
    projectId: 'rover-testing',
    storageBucket: 'rover-testing.appspot.com',
    iosBundleId: 'com.example.rovertaxi.RunnerTests',
  );
}
